name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd npm-project
          npm install

      - name: Run Jest Tests
        run: |
          cd npm-project
          npm test

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: npm-project/dist

