name: Secret Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "API_KEY=${API_KEY}" >> $GITHUB_ENV

